openapi: 3.0.0
info:
  title: API de Livraria
  description: API para gerenciamento de usuários, autores e livros
  version: "1.0.0"

servers:
  - url: http://localhost:3000/api

tags:
  - name: Usuários
    description: Operações relacionadas a usuários
  - name: Autores
    description: Operações relacionadas a autores
  - name: Livros
    description: Operações relacionadas a livros

paths:
  /users:
    get:
      tags: [Usuários]
      summary: Lista todos os usuários
      security:
        - githubOAuth: []
      responses:
        "200":
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [Usuários]
      summary: Cria um novo usuário
      security:
        - githubOAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        "201":
          description: Usuário criado com sucesso

  /users/{id}:
    get:
      tags: [Usuários]
      summary: Busca um usuário por ID
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: Usuário não encontrado
    put:
      tags: [Usuários]
      summary: Atualiza um usuário
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        "200":
          description: Atualizado com sucesso
    delete:
      tags: [Usuários]
      summary: Remove um usuário
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Removido com sucesso

  /autores:
    get:
      tags: [Autores]
      summary: Lista todos os autores
      security:
        - githubOAuth: []
      responses:
        "200":
          description: Lista de autores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Autor'
    post:
      tags: [Autores]
      summary: Cria um novo autor
      security:
        - githubOAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorInput'
      responses:
        "201":
          description: Autor criado com sucesso

  /autores/{id}:
    get:
      tags: [Autores]
      summary: Busca autor por ID
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Autor encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Autor'
        "404":
          description: Autor não encontrado
    put:
      tags: [Autores]
      summary: Atualiza um autor
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorInput'
      responses:
        "200":
          description: Autor atualizado com sucesso
    delete:
      tags: [Autores]
      summary: Remove um autor
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Autor removido com sucesso

  /livros:
    get:
      tags: [Livros]
      summary: Lista todos os livros
      security:
        - githubOAuth: []
      responses:
        "200":
          description: Lista de livros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Livro'
    post:
      tags: [Livros]
      summary: Cria um novo livro
      security:
        - githubOAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LivroInput'
      responses:
        "201":
          description: Livro criado com sucesso

  /livros/{id}:
    get:
      tags: [Livros]
      summary: Busca livro por ID
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Livro encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livro'
        "404":
          description: Livro não encontrado
    put:
      tags: [Livros]
      summary: Atualiza um livro
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LivroInput'
      responses:
        "200":
          description: Livro atualizado com sucesso
    delete:
      tags: [Livros]
      summary: Remove um livro
      security:
        - githubOAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Livro removido com sucesso

components:
  securitySchemes:
    githubOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/authorize
          tokenUrl: https://github.com/login/oauth/access_token
          scopes:
            read:user: Leitura de dados do perfil do usuário
            user: Acesso completo aos dados do usuário autenticado

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        password:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    UserInput:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - nome
        - email
        - password

    Autor:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    AutorInput:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
      required:
        - nome
        - email

    Livro:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        autorId:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string

    LivroInput:
      type: object
      properties:
        nome:
          type: string
        autorId:
          type: integer
      required:
        - nome
        - autorId
